name: Bug Report2
description: Create a bug report to help us improve
labels: [bug, no-bot]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this issue! :hugs:
        
        However note the following before opening an issue:
        * IF YOU DON'T FILL IN THE TEMPLATE, YOUR ISSUE IS LIABLE TO BE CLOSED.

  - type: checkboxes
    id: checklist
    attributes:
      label: "Checklist"
      options:
        - label: "I am able to reproduce the bug with the latest version"
          required: true
        - label: "I checked, but didn't find any duplicates (open OR closed) of this issue in the repo"
          required: true
        - label: "I have read the contribution guidelines given at XY"
          required: true
        - label: "This issue contains only one bug. I will open one issue for every bug report I want to file."
          required: true

  - type: input
    id: version
    attributes:
     label: Affected version
     description: "What version are you currently using?"
     placeholder: "x.xx.x (you can check this with the `packageVersion` R function.)"
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce the bug
      description: |
        Please add all the code necessary to reproduce the bug here (step-by-step).
        By 'reproduce', we mean that someone else can copy and paste the exact same code into their R console, execute it, and get the exact same output as you.
        
        This means you need to define all variables *within* the example, including data.
        You can upload a small sample of your data by dragging-and-dropping it into this Issue. 
        Alternatively, you can include code to create some dummy data that reproduces the error. 
        If that's not possible, please at least include a screenshot of your data and other relevant details.
        
        See [here](https://www.r-bloggers.com/2020/10/how-to-make-a-reprex/) for an intro to making a reproducible example (i.e. reprex) and why they're important! 
      placeholder: |
        df <- data.frame(list(a=rep(2,3), b=rep(1,3)))
        df["bTYPO"]
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual behavior
      description: |
        Copy and paste the R console output. 
      placeholder: |
        Error in `[.data.frame`(mtcars, "bTYPO") : undefined columns selected

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: |
        Tell us what you expect to happen.

  - type: textarea
    id: session-info
    attributes:
      label: Session info
      value: |
        - Copy and paste the output of the R function `sessionInfo()`
 
